name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - sew_style
  pull_request:
    branches:
      - main
      - sew_style

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"serviceId": "YOUR_RENDER_SERVICE_ID"}' \
          https://api.render.com/v1/services/YOUR_RENDER_SERVICE_ID/deploys
